### ISSUE TITLE
Code completion not working

### ISSUE THREAD

**Issue by skvsree** [fdecampredon/brackets-typescript#34]
Steps
1) OS Windows 8.1
2) Installed latest version of Brackets
3) Installed Brackets-TypeScript
4) created .brackets.json and added 
<pre><code>{
    "typescript": {
        "target": "ES5",
        "module": "AMD",
        "noImplicitAny": true,
        "sources" : [
            "src/declarations/**/*.ts",
            "src/main/**/*.ts"
        ]
    }
}</pre></code>
5) Still now luck for code completion of Intellisense

**Comment by basarat** [comment]
> ns//*.ts

Perhaps a single `/` and not `//`

**Comment by skvsree** [comment]
I think thats a formatting confusion due to Markdown actual value is 
  "src/declarations/**/*.ts",
   "src/main/**/*.ts"

**Comment by fdecampredon** [comment]
@skvsree if you get error in the console it would help, you can also try to debug a bit (in the worker thread try to see what's going on in 'completion service', but anyway a new version of brackets-typescript with more or less full refactoring should be ready soon.

**Comment by skvsree** [comment]
I think I figured out the issue here, if you have installed other typescript plugin it does not work.
https://github.com/tomsdev/brackets-typescript-code-intel

**Comment by fdecampredon** [comment]
o yes That plugin is a big problem it does not work anymore and take priority in brackets completion and quick edit ... I'll ask the brackets team to deactivate it .
