### ISSUE TITLE
Brackets registry shows 0.2.0

### ISSUE THREAD

**Issue by Deathspike** [fdecampredon/brackets-typescript#35]
It seems that Brackets will show the version from the 'Releases' page as shown in:

![Brackets Registry](http://puu.sh/fsi4J/365c236b67.png)

Which essentially means I can't get anywhere near the latest version. Can you make new releases?

**Comment by fdecampredon** [comment]
The latest version is still unstable it should be ready *soon* until then i won't make a release sorry

**Comment by Deathspike** [comment]
Ah, I see! It's a little annoying the extension is on TS1.0 (or something like that) when we're at 1.4. :-)

Thanks for the quick reply.

**Comment by fdecampredon** [comment]
Yup I agree once i'll publish next version everything should be fine
