### ISSUE TITLE
Protected keyword generates Typescript error 

### ISSUE THREAD

**Issue by bonometric** [fdecampredon/brackets-typescript#36]
Hi, 

Using the latest version (1.4) of Typescript, the IDE generates error TS1008 (unexpected token). Grunt-ts compiler which points to the same custom compiler path compiles successfully. I tried replacing the built-in plugin files (typescriptService.js and lib.d.ts) with no success.

Is this expected or have I made an error somewhere ?

Thanks!

**Comment by fdecampredon** [comment]
The version publish to the registry only support something compatible with the 1.0.1 release language service (1.4 is not supported) I plan to publish a new version pretty much soon (this week or the week after) sorry for the delay but it's a side work project (my company does not even use typescript at all)
